# Generated by Django 6.1 on 2026-08-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabriqx', '0003_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerCommission',
            fields=[
            ],
            options={
                'verbose_name': 'Influencer commission',
                'verbose_name_plural': 'Influencer commissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.influencercommission',),
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Influencer profile',
                'verbose_name_plural': 'Influencer profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.influencerprofile',),
        ),
        migrations.CreateModel(
            name='InfluencerReport',
            fields=[
            ],
            options={
                'verbose_name': 'Influencer report',
                'verbose_name_plural': 'Influencer reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.influencerreport',),
        ),
    ]
