# Generated by Django 6.1 on 2026-08-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerprofile',
            options={'verbose_name': 'Influencer', 'verbose_name_plural': 'Manage Influencers'},
        ),
    ]
