"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os

from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() in ('1', 'true', 'yes', 'on')

# ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if host.strip()]
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
CORS_ALLOWED_ORIGINS = {
    origin.strip().rstrip('/')
    for origin in os.getenv(
        'DJANGO_CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,https://developer-beta.com',
    ).split(',')
    if origin.strip()
}


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'fabriqx.apps.FabriqxConfig',
    'content_management.apps.ContentManagementConfig',
    'customers.apps.CustomersConfig',
    'products.apps.ProductsConfig',
    'influencers.apps.InfluencersConfig',
    'unfold',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'fabriqx.api_responses.UniformJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'EXCEPTION_HANDLER': 'fabriqx.api_responses.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'password_reset_request': '5/hour',
        'password_reset_confirm': '10/hour',
    },
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'CHECK_REVOKE_TOKEN': True,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'FABRIQX Customer & Influencer API',
    'DESCRIPTION': 'REST API for the FABRIQX React storefront and influencer dashboard.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

UNFOLD = {
    'SITE_TITLE': 'FABRIQX Admin',
    'SITE_HEADER': 'FABRIQX Administration',
    'SITE_SUBHEADER': 'Crafted for every celebration',
    'SITE_LOGO': {
        'light': '/static/branding/fabriqx-logo.jpeg',
        'dark': '/static/branding/fabriqx-logo.jpeg',
    },
    'SITE_ICON': {
        'light': '/static/branding/fabriqx-logo.jpeg',
        'dark': '/static/branding/fabriqx-logo.jpeg',
    },
    'LOGIN': {
        'image': '/static/branding/fabriqx-logo.jpeg',
    },
    'DASHBOARD_CALLBACK': 'fabriqx.dashboard.dashboard_callback',
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
    },
    'COLORS': {
        'base': {
            '50': '#f6e9d9',
            '100': '#efddc5',
            '200': '#e5d8c8',
            '300': '#d9bda8',
            '400': '#bd9478',
            '500': '#9f7358',
            '600': '#80563f',
            '700': '#5c4e3a',
            '800': '#48342a',
            '900': '#2a1e18',
            '950': '#1a1209',
        },
        'primary': {
            '50': '#fff9ed',
            '100': '#fef0cf',
            '200': '#fbdc9a',
            '300': '#f6c469',
            '400': '#e9a345',
            '500': '#cf7e27',
            '600': '#d18821',
            '700': '#88451c',
            '800': '#71391e',
            '900': '#60321e',
            '950': '#37180d',
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'fabriqx.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'fabriqx.middleware.AuditActorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'config' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('POSTGRES_DB', 'fabriqx'),
        'PORT': int(os.getenv('POSTGRES_PORT', '5432')),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': os.getenv('POSTGRES_CONN_HEALTH_CHECKS', 'true').lower() in ('1', 'true', 'yes', 'on'),
        'OPTIONS': {
            'sslmode': os.getenv('POSTGRES_SSLMODE', 'prefer'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'fabriqx.auth_backends.UsernameOrEmailBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
SHIPROCKET_EMAIL = os.environ.get('SHIPROCKET_EMAIL', '')
SHIPROCKET_PASSWORD = os.environ.get('SHIPROCKET_PASSWORD', '')
MARKETPLACE_ACCESS_KEY = os.environ.get('MARKETPLACE_ACCESS_KEY', '')
MARKETPLACE_WEBHOOK_SECRET = os.environ.get('MARKETPLACE_WEBHOOK_SECRET', '')
MARKETPLACE_CHECKOUT_URL = os.environ.get('MARKETPLACE_CHECKOUT_URL', '')
FRONTEND_RESET_PASSWORD_URL = os.environ.get('FRONTEND_RESET_PASSWORD_URL', 'http://127.0.0.1:3000/reset-password')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@fabriqx.com')
INFLUENCER_LOGIN_URL = os.environ.get('INFLUENCER_LOGIN_URL', 'http://127.0.0.1:3000/influencer/login')
PRODUCT_IMPORT_IMAGE_MAX_BYTES = int(os.environ.get('PRODUCT_IMPORT_IMAGE_MAX_BYTES', str(10 * 1024 * 1024)))
PRODUCT_IMPORT_IMAGE_TIMEOUT = int(os.environ.get('PRODUCT_IMPORT_IMAGE_TIMEOUT', '15'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': os.environ.get('EMAIL_HOST', 'localhost'),
            'port': int(os.environ.get('EMAIL_PORT', '587')),
            'username': os.environ.get('EMAIL_HOST_USER', ''),
            'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
            'use_tls': os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes', 'on'),
            'timeout': int(os.environ.get('EMAIL_TIMEOUT', '15')),
        },
    },
}
