# Generated by Django 6.1 on 2026-08-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabriqx', '0005_initialize_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.address',),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Customer profile',
                'verbose_name_plural': 'Customer profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.customerprofile',),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
            ],
            options={
                'verbose_name': 'Wishlist item',
                'verbose_name_plural': 'Wishlist items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.wishlistitem',),
        ),
    ]
