# Generated by Django 6.1 on 2026-08-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Manage Customers'},
        ),
    ]
