# Generated by Django 6.1 on 2026-08-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabriqx', '0005_initialize_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.banner',),
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
            ],
            options={
                'verbose_name': 'Homepage section',
                'verbose_name_plural': 'Homepage sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.homepagesection',),
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Newsletter subscription',
                'verbose_name_plural': 'Newsletter subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.newslettersubscription',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.testimonial',),
        ),
    ]
