# Generated by Django 6.1 on 2026-09-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_page'),
        ('fabriqx', '0019_giftsection_giftsectionfeature_giftsectionstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSection',
            fields=[
            ],
            options={
                'verbose_name': 'Homepage gift section',
                'verbose_name_plural': 'Homepage gift sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.giftsection',),
        ),
    ]
