# Generated by Django 6.1 on 2026-09-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_giftsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Hero banner', 'verbose_name_plural': 'Hero banners'},
        ),
        migrations.AlterModelOptions(
            name='homepagesection',
            options={'verbose_name': 'Homepage section setting', 'verbose_name_plural': 'Homepage section settings'},
        ),
    ]
