# Generated by Django 6.1 on 2026-09-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_alter_banner_options_alter_homepagesection_options'),
        ('fabriqx', '0020_brandlogosection_brandlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogoSection',
            fields=[
            ],
            options={
                'verbose_name': 'Brand logo section',
                'verbose_name_plural': 'Brand logo section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.brandlogosection',),
        ),
    ]
