# Generated by Django 6.1 on 2026-09-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_brandlogosection'),
        ('fabriqx', '0021_offerbanner_offergridsection_offergriditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Offer banner',
                'verbose_name_plural': 'Offer banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.offerbanner',),
        ),
        migrations.CreateModel(
            name='OfferGridSection',
            fields=[
            ],
            options={
                'verbose_name': 'Offer grid',
                'verbose_name_plural': 'Offer grid',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.offergridsection',),
        ),
    ]
