# Generated by Django 6.1 on 2026-09-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_offerbanner_offergridsection'),
        ('fabriqx', '0022_footersocialsection_footersociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialSection',
            fields=[
            ],
            options={
                'verbose_name': 'Footer social links',
                'verbose_name_plural': 'Footer social links',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.footersocialsection',),
        ),
    ]
