# Generated by Django 6.1 on 2026-09-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_footersocialsection'),
        ('fabriqx', '0023_newslettersettings_remove_testimonial_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Newsletter settings',
                'verbose_name_plural': 'Newsletter settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.newslettersettings',),
        ),
    ]
