# Generated by Django 6.1 on 2026-09-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_newslettersettings'),
        ('fabriqx', '0031_testimonial_sub_text_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
            ],
            options={
                'verbose_name': 'Brand logo',
                'verbose_name_plural': 'Brand Logo Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.brandlogo',),
        ),
    ]
