# Generated by Django 6.1 on 2026-09-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0009_brandlogo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandlogo",
            options={"verbose_name": "Brand logo", "verbose_name_plural": "Brand logos"},
        ),
    ]
