# Generated by Django 6.1 on 2026-09-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0010_alter_brandlogo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferGridItem",
            fields=[],
            options={
                "verbose_name": "Offer tile",
                "verbose_name_plural": "Offer grid",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fabriqx.offergriditem",),
        ),
    ]
