# Generated by Django 6.1 on 2026-09-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0011_offergriditem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offergriditem",
            options={"verbose_name": "Offer grid", "verbose_name_plural": "Offer grid"},
        ),
    ]
