# Generated by Django 6.1 on 2026-09-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0012_alter_offergriditem_options"),
        ("fabriqx", "0033_contactsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fabriqx.contactsubmission",),
        ),
    ]
