# Generated by Django 6.1 on 2026-08-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerReport',
            fields=[
            ],
            options={
                'verbose_name': 'Influencer report',
                'verbose_name_plural': 'Influencer reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.influencercommission',),
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory report',
                'verbose_name_plural': 'Inventory reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.productvariant',),
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Sales report',
                'verbose_name_plural': 'Sales reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.order',),
        ),
    ]
