# Generated by Django 6.1 on 2026-08-28 07:53

from django.db import migrations


def initialize_roles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    UserRole = apps.get_model('fabriqx', 'UserRole')

    groups = {
        name: Group.objects.get_or_create(name=name)[0]
        for name in ('Admin', 'Customer', 'Influencer')
    }
    for user in User.objects.all():
        role_name = 'Admin' if user.is_superuser else 'Customer'
        UserRole.objects.get_or_create(user=user, defaults={'role': role_name.lower()})
        user.groups.add(groups[role_name])


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0004_userrole'),
    ]

    operations = [
        migrations.RunPython(initialize_roles, migrations.RunPython.noop),
    ]
