# Generated by Django 6.1 on 2026-08-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0005_initialize_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
