# Generated by Django 6.1 on 2026-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0006_alter_userrole_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='tax_identifier',
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate_code',
            field=models.CharField(blank=True, db_index=True, help_text='Affiliate ID entered by the customer during checkout.', max_length=40),
        ),
    ]
