# Generated by Django 6.1 on 2026-08-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0007_remove_influencerprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='social_handle',
        ),
    ]
