# Generated by Django 6.1 on 2026-08-28 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0008_remove_influencerprofile_social_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='commission_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed commission amount'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission percentage (%)'),
        ),
    ]
