# Generated by Django 6.1 on 2026-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0010_cart_productquestion_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='influencers',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='fabriqx.influencerprofile'),
        ),
    ]
