# Generated by Django 6.1 on 2026-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0011_coupon_influencers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('categories', 'Category tiles'), ('featured', 'Featured products'), ('trending', 'Trending products'), ('new', 'New arrivals'), ('offers', 'Offers strip'), ('testimonials', 'Testimonials'), ('newsletter', 'Newsletter')], max_length=30),
        ),
    ]
