# Generated by Django 6.1 on 2026-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0017_alter_homepagesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='influencers/profiles/'),
        ),
    ]
