# Generated by Django 6.1 on 2026-09-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0018_influencerprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(help_text='Only used to identify this campaign in admin.', max_length=150)),
                ('badge_eyebrow', models.CharField(blank=True, default='With every order', max_length=100)),
                ('badge_title', models.CharField(blank=True, default='Free gift', max_length=100)),
                ('badge_icon', models.ImageField(blank=True, upload_to='gift-sections/badges/')),
                ('logo', models.ImageField(blank=True, upload_to='gift-sections/logos/')),
                ('accent_heading', models.CharField(blank=True, default='Shop More,', max_length=150)),
                ('heading', models.CharField(default='Get More Joy!', max_length=200)),
                ('description', models.TextField(blank=True, default='Every purchase comes with a free gift, just for you!')),
                ('main_image', models.ImageField(upload_to='gift-sections/main/')),
                ('gift_image', models.ImageField(blank=True, upload_to='gift-sections/gifts/')),
                ('background_image', models.ImageField(blank=True, upload_to='gift-sections/backgrounds/')),
                ('thank_you_title', models.CharField(blank=True, default='Thank you for choosing Fabriqx.', max_length=200)),
                ('thank_you_text', models.TextField(blank=True, default='Your love inspires us to keep creating styles that make every moment special.')),
                ('cta_label', models.CharField(blank=True, default='Shop now & get your free gift', max_length=150)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GiftSectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, upload_to='gift-sections/features/')),
                ('text', models.CharField(max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='fabriqx.giftsection')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GiftSectionStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, upload_to='gift-sections/statistics/')),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='fabriqx.giftsection')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
