# Generated by Django 6.1 on 2026-09-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0019_giftsection_giftsectionfeature_giftsectionstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(default='Homepage brand logos', help_text='Only used to identify this section in admin.', max_length=150)),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('background_color', models.CharField(blank=True, default='#f7e8d8', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='brand-logos/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='fabriqx.brandlogosection')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
