# Generated by Django 6.1 on 2026-09-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0020_brandlogosection_brandlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(help_text='Only used to identify this banner in admin.', max_length=150)),
                ('desktop_image', models.ImageField(upload_to='offers/banners/desktop/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='offers/banners/mobile/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('shop_now_url', models.CharField(max_length=300, verbose_name='Shop now URL')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OfferGridSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(default='Homepage offer grid', help_text='Only used to identify this section in admin.', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferGridItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(max_length=150)),
                ('desktop_image', models.ImageField(upload_to='offers/grid/desktop/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='offers/grid/mobile/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('shop_now_url', models.CharField(max_length=300, verbose_name='Shop now URL')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabriqx.offergridsection')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
