# Generated by Django 6.1 on 2026-09-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0021_offerbanner_offergridsection_offergriditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(default='Footer social links', help_text='Only used to identify this section in admin.', max_length=150)),
                ('heading', models.CharField(default='SOCIAL', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(max_length=80)),
                ('icon', models.ImageField(upload_to='footer/social-icons/')),
                ('url', models.URLField(max_length=300)),
                ('aria_label', models.CharField(blank=True, max_length=120, verbose_name='Accessibility label')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='fabriqx.footersocialsection')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
