# Generated by Django 6.1 on 2026-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0022_footersocialsection_footersociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_email', models.EmailField(help_text='New newsletter subscription notifications will be sent to this address.', max_length=254)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter settings',
            },
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='display_order',
        ),
    ]
