# Generated by Django 6.1 on 2026-09-03 06:39

import django.core.validators
from django.db import migrations, models


def initialize_global_commission(apps, schema_editor):
    InfluencerProfile = apps.get_model("fabriqx", "InfluencerProfile")
    SiteSettings = apps.get_model("fabriqx", "SiteSettings")
    influencer = (
        InfluencerProfile.objects.filter(
            is_active=True,
            commission_type="percentage",
            commission_rate__gt=0,
        ).order_by("id").first()
        or InfluencerProfile.objects.filter(
            is_active=True,
            commission_type="fixed",
            commission_fixed_amount__gt=0,
        ).order_by("id").first()
    )
    defaults = {}
    if influencer:
        defaults = {
            "commission_type": influencer.commission_type,
            "commission_rate": influencer.commission_rate,
            "commission_fixed_amount": influencer.commission_fixed_amount,
        }
    defaults["legacy_influencer_commissions"] = {
        str(profile.pk): {
            "commission_type": profile.commission_type,
            "commission_rate": str(profile.commission_rate),
            "commission_fixed_amount": str(profile.commission_fixed_amount),
        }
        for profile in InfluencerProfile.objects.order_by("id")
    }
    SiteSettings.objects.update_or_create(pk=1, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0024_repair_influencer_photo_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission percentage (%)')),
                ('commission_fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed commission amount')),
                ('legacy_influencer_commissions', models.JSONField(blank=True, default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.RunPython(initialize_global_commission, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='commission_fixed_amount',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='commission_type',
        ),
    ]
