# Generated by Django 6.1 on 2026-09-04 05:41

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0027_make_product_description_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='banners/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='brand-logos/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='categories/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='footersociallink',
            name='icon',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='footer/social-icons/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='gift-sections/backgrounds/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsection',
            name='badge_icon',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='gift-sections/badges/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsection',
            name='gift_image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='gift-sections/gifts/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsection',
            name='logo',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='gift-sections/logos/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsection',
            name='main_image',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='gift-sections/main/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsectionfeature',
            name='icon',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='gift-sections/features/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='giftsectionstatistic',
            name='icon',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='gift-sections/statistics/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='influencers/profiles/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='desktop_image',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='offers/banners/desktop/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='offers/banners/mobile/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='offergriditem',
            name='desktop_image',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='offers/grid/desktop/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='offergriditem',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='offers/grid/mobile/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='products/%Y/%m/', validators=[fabriqx.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size: 5 MB.', upload_to='testimonials/', validators=[fabriqx.models.validate_image_file_size]),
        ),
    ]
