# Generated by Django 6.1 on 2026-09-04 06:24

import django.core.validators
import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0028_alter_banner_image_alter_brandlogo_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='customer_name',
            field=models.CharField(max_length=150, validators=[fabriqx.models.validate_customer_name]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
