# Generated by Django 6.1 on 2026-09-05 09:51

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0029_alter_testimonial_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Allowed formats: JPG, JPEG, PNG, GIF. Maximum file size: 5 MB.', upload_to='banners/', validators=[fabriqx.models.validate_image_file_size, fabriqx.models.validate_banner_logo_image]),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='logo',
            field=models.ImageField(help_text='Allowed formats: JPG, JPEG, PNG, GIF. Maximum file size: 5 MB.', upload_to='brand-logos/', validators=[fabriqx.models.validate_image_file_size, fabriqx.models.validate_banner_logo_image]),
        ),
    ]
