# Generated by Django 6.1 on 2026-09-08

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabriqx", "0031_testimonial_sub_text_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                help_text="Allowed formats: JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.",
                upload_to="banners/",
                validators=[fabriqx.models.validate_image_file_size, fabriqx.models.validate_banner_logo_image],
            ),
        ),
        migrations.AlterField(
            model_name="brandlogo",
            name="logo",
            field=models.ImageField(
                help_text="Allowed formats: JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.",
                upload_to="brand-logos/",
                validators=[fabriqx.models.validate_image_file_size, fabriqx.models.validate_banner_logo_image],
            ),
        ),
    ]
