# Generated by Django 6.1 on 2026-09-09

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabriqx", "0033_contactsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftsection",
            name="badge_icon",
            field=models.FileField(blank=True, help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/badges/", validators=[fabriqx.models.validate_icon_file]),
        ),
        migrations.AlterField(
            model_name="giftsectionfeature",
            name="icon",
            field=models.FileField(blank=True, help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/features/", validators=[fabriqx.models.validate_icon_file]),
        ),
        migrations.AlterField(
            model_name="giftsectionstatistic",
            name="icon",
            field=models.FileField(blank=True, help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/statistics/", validators=[fabriqx.models.validate_icon_file]),
        ),
        migrations.AlterField(
            model_name="footersociallink",
            name="icon",
            field=models.FileField(help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="footer/social-icons/", validators=[fabriqx.models.validate_icon_file]),
        ),
    ]
