# Generated by Django 6.1 on 2026-09-09

from django.db import migrations, models


def normalize_platform_names(apps, schema_editor):
    FooterSocialLink = apps.get_model("fabriqx", "FooterSocialLink")
    names = {
        "facebook": "facebook",
        "x": "x",
        "linkedin": "linkedin",
        "instagram": "instagram",
    }
    for link in FooterSocialLink.objects.all():
        normalized = names.get((link.platform_name or "").strip().lower())
        if normalized:
            link.platform_name = normalized
            link.save(update_fields=("platform_name",))


def reverse_normalize_platform_names(apps, schema_editor):
    # Keeping lowercase stable values is safe when rolling back this migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fabriqx", "0034_svg_capable_icon_uploads"),
    ]

    operations = [
        migrations.RemoveField(model_name="footersociallink", name="icon"),
        migrations.RunPython(normalize_platform_names, reverse_normalize_platform_names),
        migrations.AlterField(
            model_name="footersociallink",
            name="platform_name",
            field=models.CharField(choices=[("facebook", "Facebook"), ("x", "X"), ("linkedin", "LinkedIn"), ("instagram", "Instagram")], max_length=20),
        ),
        migrations.AddConstraint(
            model_name="footersociallink",
            constraint=models.UniqueConstraint(fields=("section", "platform_name"), name="unique_footer_social_platform"),
        ),
    ]
