# Generated by Django 6.1 on 2026-09-09

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabriqx", "0035_footer_social_links_fixed_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftsection",
            name="logo",
            field=models.FileField(blank=True, help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/logos/", validators=[fabriqx.models.validate_icon_file]),
        ),
        migrations.AlterField(
            model_name="giftsection",
            name="main_image",
            field=models.FileField(help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/main/", validators=[fabriqx.models.validate_icon_file]),
        ),
        migrations.AlterField(
            model_name="giftsection",
            name="gift_image",
            field=models.FileField(blank=True, help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/gifts/", validators=[fabriqx.models.validate_icon_file]),
        ),
        migrations.AlterField(
            model_name="giftsection",
            name="background_image",
            field=models.FileField(blank=True, help_text="Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.", upload_to="gift-sections/backgrounds/", validators=[fabriqx.models.validate_icon_file]),
        ),
    ]
