# Generated by Django 6.1 on 2026-09-09 10:36

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0036_gift_section_svg_capable_visuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Allowed formats: JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB. Hero banner images are automatically center-cropped and resized to 1920 × 890 pixels.', upload_to='banners/', validators=[fabriqx.models.validate_image_file_size, fabriqx.models.validate_banner_logo_image]),
        ),
    ]
