# Generated by Django 6.1 on 2026-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0037_auto_resize_hero_banner_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
