# Generated by Django 6.1 on 2026-09-10

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabriqx", "0038_customer_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Maximum file size: 5 MB.",
                upload_to="customers/profiles/",
                validators=[fabriqx.models.validate_image_file_size],
            ),
        ),
    ]
