# Generated by Django 6.1 on 2026-09-10 11:31

import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0040_product_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Allowed formats: SVG, JPG, JPEG, PNG, GIF, WEBP. Maximum file size: 5 MB.', upload_to='customers/profiles/', validators=[fabriqx.models.validate_profile_image]),
        ),
    ]
