# Generated by Django 6.1 on 2026-09-10 12:09

import django.db.models.deletion
import fabriqx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0041_allow_svg_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Maximum file size: 5 MB.', upload_to='reviews/%Y/%m/', validators=[fabriqx.models.validate_image_file_size])),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fabriqx.review')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
