# Generated by Django 6.1 on 2026-08-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabriqx', '0003_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.category',),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.inventorymovement',),
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory report',
                'verbose_name_plural': 'Inventory reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.inventoryreport',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.product',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.productimage',),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.productvariant',),
        ),
    ]
