# Generated by Django 6.1 on 2026-09-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabriqx', '0041_allow_svg_customer_profile_image'),
        ('products', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.productfaq',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fabriqx.review',),
        ),
    ]
